import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  variable: '--font-anton',
  subsets: ["latin"],
  weight: "400"
})

const fixedSys = localFont({
  variable: '--font-fixedSys',
  src: '../public/fonts/FSEX300.ttf'
})

const JetBrainsMono = localFont({
  variable: '--font-jetbrainsmono',
  src: [
    { path: '../public/webfonts/JetBrainsMono-ExtraLight.woff2', weight: '200' },
    { path: '../public/webfonts/JetBrainsMono-Light.woff2',      weight: '300' },
    { path: '../public/webfonts/JetBrainsMono-Regular.woff2',    weight: '400' },
    { path: '../public/webfonts/JetBrainsMono-Medium.woff2',     weight: '500' },
    { path: '../public/webfonts/JetBrainsMono-SemiBold.woff2',   weight: '600' },
    { path: '../public/webfonts/JetBrainsMono-Bold.woff2',       weight: '700' },
    { path: '../public/webfonts/JetBrainsMono-ExtraBold.woff2',  weight: '800' },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${fixedSys.variable} ${JetBrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
